baseURL = 'https://bubfcg.github.io/Test-Website/'
languageCode = 'nl-nl'
title = 'C.A. Holland Conventie 2026'

[params]
  # Hoofdkleuren uit stijlgids
  color_blue = "#5EBBEC"
  color_yellow = "#FEEB15"
  color_orange = "#ED6D1A"
  
  # Sectie kleuren (tinten uit stijlgids)
  color_olive_bg = "#8A9127"
  color_dark_olive_bg = "#5A5E1A"
  color_dark_blue_bg = "#0A3D5B"
  
  countdown_target = "2026-08-14T09:00:00"

