baseURL = 'https://example.org/'
languageCode = 'nl-nl'
title = 'Mijn Hugo Website'
theme = ''

[params]
  description = 'Een moderne website gebouwd met Hugo'
  author = 'Jouw Naam'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = 'Over'
    url = '/about/'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
